apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: coroot-operator
  name: coroot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coroot-operator
  namespace: coroot
  labels:
    app.kubernetes.io/name: coroot-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: coroot-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: coroot-operator
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: operator
        image: ghcr.io/coroot/coroot-operator:latest
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 64Mi
      serviceAccountName: coroot-operator
      terminationGracePeriodSeconds: 10
